version: '3.8'

services:
  api:
    build: .
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      DATABASE_URL: mysql://root:password@mysql_db:3306/logique_test_db
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: logique_test_db
